session: simple
plugins:
        Auth::Extensible:
            no_default_pages: 1
            realms:
                config:
                    provider: Config
                    users:
                        - user: steve
                          pass: secret!
plack_middlewares:
  -
    - ReverseProxy
