#!/bin/sh
#
# Launch the application, in production, with a per-day log-file
#

exec plackup -s Twiggy --workers=4 -0 127.0.0.1 -p 5151 -a ./bin/purple.psgi \
        --access-log logs/access.$(date +%Y-%m-%d).log -E production
